filebeat.inputs:
  - type: log
    paths:
      - /usr/share/services/nginx/access.log
    fields:
      apache: true
    fields_under_root: true
  
output.kafka:
  hosts: ["kafka1:29092", "kafka2:39093", "kafka3:49094"]
  topic: 'stlog'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: none
  max_message_bytes: 1000000
